# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


get_data <- function(n, p, beta, varr1, alpha, mu2, varr2, c_r, seed = 1L) {
    .Call(`_ASDAR_get_data`, n, p, beta, varr1, alpha, mu2, varr2, c_r, seed)
}

get_weight <- function(x, y, status) {
    .Call(`_ASDAR_get_weight`, x, y, status)
}

get_weighted_data <- function(n, p, beta, varr1, alpha, mu2, varr2, c_r, seed = 1L) {
    .Call(`_ASDAR_get_weighted_data`, n, p, beta, varr1, alpha, mu2, varr2, c_r, seed)
}

F_function <- function(ita, x_ita, y_ita) {
    .Call(`_ASDAR_F_function`, ita, x_ita, y_ita)
}

DF_function <- function(ita, x_ita, y_ita) {
    .Call(`_ASDAR_DF_function`, ita, x_ita, y_ita)
}


Sdar <- function(ita0, T1, x, y, tau1, dd, iter_max) {
    .Call(`_ASDAR_Sdar`, ita0, T1, x, y, tau1, dd, iter_max)
}

Asdar <- function(x, y, varr2, ita0, tau, tau1, dd, iter_max) {
    .Call(`_ASDAR_Asdar`, x, y, varr2, ita0, tau, tau1, dd, iter_max)
}

